Chain id must be an int not str
nucypher/tdec-nft-example pull request #6
Opened 2022-11-10 13:05 UTC by theref

2022-11-10 13:13 UTC, piotr-roslaniec approved these changes

2022-11-10 14:06 UTC, KPrasch requested changes
Hmm there still appears to be an issue validating the chain.

![Screenshot from 2022-11-10 13-12-00](https://user-images.githubusercontent.com/679404/201112713-91f7dbd9-b430-43a7-bad2-d13d773fd6ad.png)

2022-11-10 14:35 UTC, KPrasch commented
After further discussion we discovered the issue I posted above is caused by lack of chain ID support in nucypher-ts-alpha.24.

2022-11-11 18:28 UTC, KPrasch commented
All issues resolved by bumping to `nucypher/nucypher-ts@v0.7.9-alpha.25`

2022-11-11 18:28 UTC, KPrasch approved these changes

2022-11-11 18:29 UTC, merged